language: python
python:
  - "3.8"
install:
  # Install phase of our CI pipeline
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a

  - conda create -q -n project python=$TRAVIS_PYTHON_VERSION numpy scipy nose coverage coveralls sphinx sphinx_rtd_theme
  - conda activate project
  
script:
  - nosetests -sv --with-coverage --cover-package=. test.py
  - coveralls
