language: python
python:
  - "3.8"
install:
  - pip install .
  - pip install -r build-requirements.txt
  
script:
  - run-house-prices-pred  #test if the cmdline app runs at least
  # Run phase of our CI pipeline
  - nosetests -sv --with-coverage --cover-package=house_prices_m05_pkg house_prices_m05_pkg
  - sphinx-build -b doctest doc sphinx
  # Build docs
  - sphinx-build doc sphinx
  - touch sphinx/.nojekyll
  - coveralls

deploy:
  - provider: pages:git
    verbose: true
    edge: true
    token: $GITHUB_TOKEN
    local_dir: ./sphinx/
    on:
        branch: master
        condition: $TRAVIS_PYTHON_VERSION = 3.8
