language: python
python:
  - "3.8"
install:
  # Install phase of our CI pipeline
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a

  - conda create -q -n project python=$TRAVIS_PYTHON_VERSION numpy scipy nose coverage coveralls sphinx sphinx_rtd_theme pandas matplotlib scikit-learn
  - conda activate project
  
script:
  # Run phase of our CI pipeline
  - nosetests -sv --with-coverage --cover-package=. ./py_scripts/test_toolchain.py
  - sphinx-build -b doctest doc sphinx
  # Build docs
  - sphinx-build doc sphinx
  - touch sphinx/.nojekyll
  - coveralls

deploy:
  - provider: pages:git
    verbose: true
    edge: true
    token: $GITHUB_TOKEN
    local_dir: ./sphinx/
    on:
        branch: master
        condition: $TRAVIS_PYTHON_VERSION = 3.8